version: '3'

networks:
  host:

services:
  instance:
    image: lekpamartin/docker-bench-security-exporter
    restart: unless-stopped
    networks: 
      - host
    ports:
      - 9700:9700
    read_only: true
    volumes:
        - /var/lib/docker:/var/lib/docker
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/lib/systemd:/usr/lib/systemd
        - /etc/docker:/etc/docker
        - /usr/bin/docker-containerd:/usr/bin/docker-containerd
        - /usr/bin/docker-runc:/usr/bin/docker-runc
