version: '3'

services:
  docker-bench-security-exporter:
    image: lekpamartin/docker-bench-security-exporter
    restart: unless-stopped
    net: host
    ports:
      - 9700:9700
    read_only: true
    volumes:
        - /var/lib:/var/lib
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/lib/systemd:/usr/lib/systemd
        - /etc:/etc
