version: '3'

networks:
  host:

services:
  instance:
    image: lekpamartin/docker-bench-security-exporter
    labels:
      - co.elastic.logs/disable=true
    restart: unless-stopped
    networks: 
      - host
    ports:
      - 9700:9700
    volumes:
        - /etc/default/docker:/etc/default/docker:ro
        - /etc/docker:/etc/docker:ro
        - /usr/bin/docker-containerd:/usr/bin/docker-containerd:ro
        - /usr/bin/docker-runc:/usr/bin/docker-runc:ro
        - /var/lib/docker:/var/lib/docker:ro
        - /usr/lib/systemd:/usr/lib/systemd:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - check.env
